version: "3"

services:
  composer:
    image: "composer:latest"
    volumes:
      - ".:/app"
    command:
      - "install"
      - "--ignore-platform-reqs"
      - "--no-interaction"
      - "--no-plugins"
      - "--no-scripts"
      - "--prefer-dist"

  app:
    build: "./docker"
    container_name: "app"
    depends_on:
      - "composer"
    volumes:
      - ".:/app"
    environment:
      POPPLER_PHP_BIN_DIR: "/usr/bin"
